services:
  typesense:
    image: typesense/typesense:29.0
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    command: '--api-key=${TYPESENSE_API_KEY} --data-dir=/data --enable-cors'

  typesense-dashboard:
    image: bfritscher/typesense-dashboard:2.1
    container_name: typesense-dashboard
    ports:
      - "8080:80"
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_HOST: http://localhost:8108
    depends_on:
      - typesense

volumes:
  typesense-data: